language: java
jdk:
  - oraclejdk7
  - openjdk7
before_script: chmod a+x build.sh
script: "./build.sh"
deploy:
  provider: releases
  api-key: "97:ca:4a:1f:b2:43:8d:ea:69:96:c6:12:6d:57:97:20"
  file: "./build/jar/NextParkour.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  email: false
