language: java
jdk:
  - oraclejdk7
  - openjdk7
before_script: chmod a+x build.sh
script: "./build.sh"
deploy:
  provider: releases
  api-key: "640acc30a639177e049de8b56f355e734ca83c66"
  file: "./build/jar/NextParkour.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  email: false
