name: NEXTparkour
main: com.gmail.alikstudio47.NEXTparkour
version: 1.3
commands:
   nextparkour:
      description: Uruchamia plugin NEXTparkour
      aliases: [np, nparkour]
      usage: /np
   nextparkouradmin:
      description: Uruchamia administracje pluginu NEXTparkour
      aliases: [npa, nparkouradmin]
      usage: /npa
