name: NEXTparkour
main: com.gmail.alikstudio47.NEXTparkour
version: 1.2
commands:
   nextparkour:
      description: Uruchamia plugin NEXTparkour
      aliases: [np, nparkour]
      usage: /np
      permission: np.use
      permission-message: Nie masz uprawnien. Serio1.
   nextparkouradmin:
      description: Uruchamia administracje pluginu NEXTparkour
      aliases: [npa, nparkouradmin]
      usage: /npa
      permission: np.admin
      permission-message: Nie masz uprawnien. Serio.